### ISSUE TITLE
Some Suggestions

### ISSUE THREAD

**Issue by Mahan3340** [zhuxb711/FileManager#1]
Hi, here are some feature suggestions

- Add file and folder selection Option: select multiple files or folders to copy/cut/delete/
- The language is kind of mixed up. English + Chinese (?) on many pages. Please add an option in the setting page to select a language and use that for every word in each page
- Add an option to drag and drop between tabs
- Add an option to remove the default pinned folders to the home screen ( Documents, Music,...)
- Typo (Setting->Personalize)
- The back button does not work in the setting page (disabled)
- Removing the (+) Button in the QuickView Causes the app to crash

Thanks for your great app and sorry to bring up the issues and suggestions here, I could not submit my feedback within the app (Network Error)

**Comment by zhuxb711** [comment]
@Mahan3340 

- You can use keyboard shortcuts to select multiple files/folders

- Because RX is developed and maintained by individuals, there may be some problems in multilingual translation. If you find any incomplete translation, please submit it to me here, thank you

- Currently, dragging between tabs is not supported yet, I will try to achieve

- I will change the mechanism to allow remove the default pinned folders

- Thank you for correcting the translation (Personalise->Personalize)

- The settings page is a pop-up control, so it does not need to use the back button, this is not a BUG

What does this mean ?
> Removing the (+) Button in the QuickView Causes the app to crash

**Comment by Mahan3340** [comment]
@zhuxb711 Thank for your response. I've attached a screenshot for the plus button I mentioned earlier. By the way, I'm using a surface with a touch screen with no keyboard and the issues are when working with a touch screen. I would appreciate it if your team could test the app with a touch screen and make it a little bit more touch-friendly.

![photo_2020-05-03_11-01-17](https://user-images.githubusercontent.com/21075867/80907630-d54f2500-8d2d-11ea-9042-69c938892c45.jpg)

**Comment by zhuxb711** [comment]
@Mahan3340 

Sorry for the inconvenience. 

> Long-Press a file to open a menu, then try to select open-with, Edit or share with a touch screen, works well with mouse or pen but not finger

This situation is Microsoft's fault😂😂😂😂😂.
See this: [How to use menuflyout in CommandBarFlyout with touch screen](https://github.com/microsoft/microsoft-ui-xaml/issues/2040)

Also, I don’t know how you removed the “+” button, because from a code perspective you should not be able to right-click and remove it. How did you do it?

**Comment by Mahan3340** [comment]
@zhuxb711 So we have to wait for MX to fix it 😁 I guess top/bottom menus for copy/cut/selection/delete,.. shortcuts would be a good alternative, just like the win phone old apps or some other UWP apps, with the 3-dot menu.
The plus button could be deleted by a long-press menu using touch.

**Comment by zhuxb711** [comment]
@Mahan3340 

I have investigated the problems when using the touch screen.

The cause of this problem is that mouse events and touch events are triggered in different ways
So, I will fix the issue that may cause the right-click menu to pop up incorrectly when using the touch screen in the next version.

**Comment by zhuxb711** [comment]
Close #1
Most of this recommendation has been implemented in Release-4.6.8
v4.6.8 has been released to Microsoft Store
